### ISSUE TITLE
[Guides] - Complete Guide to Solana Development

### ISSUE THREAD

**Issue by aeither** [solana-foundation/developer-content#103]
### Problem

Everyone is looking for a complete guide to Solana development to get them started. Guides like [https://dev.to/edge-and-node/the-complete-guide-to-full-stack-solana-development-with-react-anchor-rust-and-phantom-3291 ](https://dev.to/edge-and-node/the-complete-guide-to-full-stack-solana-development-with-react-anchor-rust-and-phantom-3291)were essential to jumpstarting the ecosystem in 2021, and we're looking for a refresh. Proper submission must be made as a PR to https://github.com/solana-foundation/developer-content.

### Proposed Solution

Complete Guide to Solana Development Updated with the latest tooling and libraries with code repo.

**Comment by nickfrosty** [comment]
closed with the PR
