### ISSUE TITLE
Erroneous `Result` in table of contents

### ISSUE THREAD

**Issue by jacobcreech** [solana-foundation/developer-content#110]
### Problem

Finding `Result` in random places in the table of contents. Picture shown for https://solana.com/docs/more/exchange#the-importance-of-implementing-priority-fees

<img width="247" alt="Screen Shot 2024-03-07 at 9 27 22 PM" src="https://github.com/solana-foundation/developer-content/assets/82475023/33fd0a21-21a2-4559-8340-2d68e02cfa4f">

### Suggested FIx

Get rid of whatever this erroneous `Result` is

**Comment by nickfrosty** [comment]
This was fixed in #112
