### ISSUE TITLE
Eye strain when reading docs in dark mode

### ISSUE THREAD

**Issue by osmanbowser** [solana-foundation/developer-content#141]
### Problem
Dark mode is great, but light mode should be an option too.

### Proposed Solution
Add a toggle switch, or use device settings, to switch between light and dark mode in the developer docs.

**Comment by osmanbowser** [comment]
It's simple to do, since it's TailwindCSS. What do you all think?

**Comment by nickfrosty** [comment]
We are actively working on this! Hopefully it will be live soon, tm :)

**Comment by osmanbowser** [comment]
Great! I'd be happy to help if you all need it.

**Comment by jacobcreech** [comment]
@osmanbowser wdyt about the newest docs?

**Comment by osmanbowser** [comment]
@jacobcreech they look great! Day and night difference
