### ISSUE TITLE
Web content cutoff on mobile and words mashed together

### ISSUE THREAD

**Issue by osmanbowser** [solana-foundation/developer-content#142]
When accessing https://solana.com/staking#what-is-staking using mobile (iPhone 14), the text is cutoff and a few words are misspelled/smashed together.

![image](https://github.com/solana-foundation/developer-content/assets/20252960/c66a0511-22cf-4101-88a3-bffbaf8fd1ce)

The page doesn't allow you to scroll left or right to read the content.

I looked for the main site repo but it doesn't appear to be open source.

**Comment by nickfrosty** [comment]
@osmanbowser a fix was shipped to solana.com. Can you take a look and see if you are still having issues?
You might need to hard refresh your browser (which can sometimes be finicky on mobile)

**Comment by osmanbowser** [comment]
@nickfrosty the site looks way better. Great work!
