### ISSUE TITLE
redirects on `docs.solana.com` links

### ISSUE THREAD

**Issue by nickfrosty** [solana-foundation/developer-content#147]
### Problem

There are many links to `docs.solana.com` within this repo which has been converted to only handling redirects. We can and should avoid these redirects by just putting in their final destination

### Proposed Solution

Now that the docs migration is completed, all of these links should be updated to their new/correct locations

**Comment by rohitt-gupta** [comment]
is this the updated link?
https://solana.com/docs
i will make a pr for it if you can confirm ? @nickfrosty

**Comment by jacobcreech** [comment]
@rohitt-gupta that is the updated root for all docs.

**Comment by nickfrosty** [comment]
all these links have been addressed and updated accordingly in https://github.com/solana-foundation/developer-content/pull/483
