### ISSUE TITLE
[guide] improve local rust hello world

### ISSUE THREAD

**Issue by nickfrosty** [solana-foundation/developer-content#207]
### Problem

the [rust hello world guide](https://solana.com/developers/guides/getstarted/local-rust-hello-world) should be improved after feedback during a DX test

### Proposed Solution

- add clear instructions on installing the solana cli locally - https://solana.com/developers/guides/getstarted/local-rust-hello-world#install-rust-and-cargo
- add instructions on creating the local keypair before running the validator
- add instructions for airdropping on running the local validator
- add info around needing to create a keypair and airdrop before running the program deploy command here https://solana.com/developers/guides/getstarted/local-rust-hello-world#deploy-your-solana-program

**Comment by michaelcrypt0x** [comment]
I think basic inputs are missing for the project to compile (dependencies and dev-dependencies )
