### ISSUE TITLE
Code formatting is off in Wallet Adapter guide

### ISSUE THREAD

**Issue by heyAyushh** [solana-foundation/developer-content#262]
### Problem
Code formatting is off 
https://solana.com/developers/guides/wallets/add-solana-wallet-adapter-to-nextjs#setup-the-appwalletprovider

Is coming from this file
https://github.com/solana-foundation/developer-content/blob/main/content/guides/wallets/add-solana-wallet-adapter-to-nextjs.md

**Comment by nickfrosty** [comment]
Nice catch @heyAyushh. I am working on some fixes for this now. It looks like during my recent fixes for translation things is when it started altering the code blocks (specifically when code blocks contain html/jsx style components `<whatever>`
