### ISSUE TITLE
Update CI to allow GitHub UI commits

### ISSUE THREAD

**Issue by mikemaccana** [solana-foundation/developer-content#267]
### Problem

We get external contribs like https://github.com/solana-foundation/developer-content/pull/257 that can't be merged automatically because they've either been done via GitHub UI (which doesn't format on save) or someone doesn't have format on save set up.

We then have to pull down the repo and manually format.

### Proposed Solution

Fix formatting after merge in GitHub CI.

**Comment by nickfrosty** [comment]
I had added some for running and merging prettier via a tag, but it was super finicky
https://github.com/solana-foundation/developer-content/blob/main/.github/label-actions.yml
