### ISSUE TITLE
@metaplex-foundation/js is deprecated

### ISSUE THREAD

**Issue by Mishragini** [solana-foundation/developer-content#326]
### Problem

While going through this [Solana tutorial](https://solana.com/developers/courses/tokens-and-nfts/nfts-with-metaplex#lab), I found that the package used is deprecated and no longer in use.

### Proposed Solution

1. **Update the Tutorial:** Replace references to the deprecated package with the latest version or alternative packages currently recommended by the Metaplex and Solana communities.

2. **Provide Guidance for Migration:** Include a section or link to resources that help developers migrate from the deprecated package to the new package, including any changes in the API or best practices.

3. **Code Example Updates:** Update all code examples in the tutorial to align with the new packages, ensuring they work with the current Solana and Metaplex SDK versions.

4. **Deprecation Notice:** Add a notice at the beginning of the tutorial informing developers of the deprecation and directing them to the updated resources.

**Comment by mikemaccana** [comment]
Thanks @Mishragini ! We did deliberately choose the older, non-Umi version of Metaplex when writing this chapter as it's the most popular JS SDK and less complicated than Umi (there's actually [a notice about this in the tutorial](https://solana.com/developers/courses/tokens-and-nfts/nfts-with-metaplex#the-metaplex-token-metadata-program), but it looks like [Metaplex officially deprecated the JS SDK](https://github.com/metaplex-foundation/js) a few weeks ago and seems to have [marked the JS SDK NPM package](https://www.npmjs.com/package/@metaplex-foundation/js) as deprecated at the same time. 

We do have Umi code ready to go,

**Comment by mikemaccana** [comment]
I'm assigning myself till all the courses are updated then will ping my colleagues about the other content
.
