### ISSUE TITLE
The configured font color is difficult to see after running it locally.

### ISSUE THREAD

**Issue by flingjie** [solana-foundation/developer-content#361]
### Problem
I'm not sure if it's an issue with my local computer; the effect is as follows.
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/75463064-62d0-43b2-a5c3-47be3ac74431">

**Comment by akhilesh-w** [comment]
can you link the page where you got this issue?

**Comment by flingjie** [comment]
This problem cannot be reproduced with the latest version.
