### ISSUE TITLE
can't import metaplex-foundation/mpl-token-metadata 

### ISSUE THREAD

**Issue by Karimium0** [solana-foundation/developer-content#39]
using the playground, i can't seem to import nor use metaplex-foundation/mpl-token-metadata's modules using the latest version. I'm not sure which modules are accessible using the playground. A guide on setting up token information using the playground would be great.

**Comment by nickfrosty** [comment]
Playground specific issues should be opened on the Playground's github repo:
https://github.com/solana-playground/solana-playground
