### ISSUE TITLE
`anchor_movie_review_program::update_movie_review` do not sanitize `rating` parameter

### ISSUE THREAD

**Issue by T-Mathieu** [solana-foundation/developer-content#431]
### Problem
[update_movie_review](https://github.com/solana-foundation/developer-content/blob/3c43753d7b929b04979c03071aa3f99a5f4111d7/content/courses/onchain-development/anchor-pdas.md?plain=1#L636C5-L654C2) do not include any check on the `rating` input, allowing the `rating` to be out of the 1-5 limit.

This test highlights the situation:

```js
it("Movie review is updated with incorrect rating`", async () => {
    const newDescription = "Wow this is new";
    const newRating = 10; // Rating should not be above 5
   
    const tx = await program.methods
      .updateMovieReview(movie.title, newDescription, newRating)
      .rpc();
   
    const account = await program.account.movieAccountState.fetch(moviePda);
    expect(newRating === account.rating);
    expect(newDescription === account.description);
  });
```

### Proposed Solution
Add the same `require!` in `update_movie_review` as in `add_movie_review`:

```rust
require!(rating >= MIN_RATING && rating <= MAX_RATING, MovieReviewError::InvalidRating);
```

**Comment by rishabhguptareal** [comment]
can you assign this
