### ISSUE TITLE
[docs] install page does not use `avm`

### ISSUE THREAD

**Issue by nickfrosty** [solana-foundation/developer-content#436]
### Problem

the [installation page does](https://solana.com/docs/intro/installation#install-anchor-cli) not use `avm` to install the anchor cli.

### Proposed Solution

update this doc page to install avm, install the desired anchor version, and use that anchor version via `avm`

**Comment by ZYJLiu** [comment]
avm doesn't work anymore it throws errors

**Comment by nickfrosty** [comment]
@ZYJLiu installing anchor does not work with the specific version of rust, which is covered in our install doc already
