### ISSUE TITLE
Lab link returns 404 page

### ISSUE THREAD

**Issue by dvrvsimi** [solana-foundation/developer-content#507]
### Problem
[link to starter lab](https://github.com/Unboxed-Software/anchor-custom-macro/tree/starter) in the `rust-macros.md` file for the [rust macros lesson](https://github.com/solana-foundation/developer-content/blob/main/content/courses/program-optimization/rust-macros.md) returns a 404 page

### Proposed Solution
searched the [unboxed software](https://github.com/Unboxed-Software) repo but found no backup so idk

**Comment by dvrvsimi** [comment]
@mikemaccana this lesson is important for improving the `rust-macros.md` lesson, will be waiting
cheers

**Comment by mikemaccana** [comment]
Does this still happen? The starter lab link is to now https://github.com/solana-developers/anchor-custom-macro/tree/starter which exists.

**Comment by mikemaccana** [comment]
Sorry I didn't mean to close.

**Comment by dvrvsimi** [comment]
it's alright, was looking to attempt an improvement on `rust-macros.md` but someone did it already

closing now, thanks...
