### ISSUE TITLE
`getTokenAccountsByOwner` expects at least 2 arguments

### ISSUE THREAD

**Issue by abba0110** [solana-foundation/developer-content#520]
### Problem

Steps to reproduce:
1. Go to https://solana.com/docs/rpc/http/gettokenaccountsbyowner
2. Observe 1 *required* field
3. Copy code sample
4. Exclude *optional* fields from code sample
5. Execute command
    ```bash
    curl https://api.devnet.solana.com -X POST -H "Content-Type: application/json" -d '
      {
        "jsonrpc": "2.0",
        "id": 1,
        "method": "getTokenAccountsByOwner",
        "params": [
          "4Qkev8aNZcqFNSRhQzwyLMFSsi94jHqE8WNVTJzTP99F"
        ]
      }
    '
    ```
6. Expected: System returns token accounts
7. Actual: System returns error
    ```bash
    {"jsonrpc":"2.0","error":{"code":-32602,"message":"`params` should have at least 2 argument(s)"},"id":1}
    ```

### Proposed Solution

1. Update *required* fields in documentation

**Comment by nickfrosty** [comment]
thanks for noticing and flagging this, its now fixed :)

**Comment by abba0110** [comment]
@nickfrosty thanks.
