### ISSUE TITLE
`code` in headers mess up breadcrumbs

### ISSUE THREAD

**Issue by jacobcreech** [solana-foundation/developer-content#574]
### Problem

https://solana.com/docs/programs/deploying#how-object-object-works leads to `How solana program deploy works`, but the breadcrumb name doesn't match right

### Proposed Solution

Make the breadcrumb match correctly

**Comment by nickfrosty** [comment]
this bug would actually need to be fixed in the solana-com repo

**Comment by ZYJLiu** [comment]
I was about to just rename the htag as a temporary fix, but noticed you linked to in a twitter post. If I update it now its gonna break your link, so just going to leave it for now while I work on updating the content.

**Comment by mikemaccana** [comment]
Just a note that when this is fixed in solana-com we should update https://github.com/solana-foundation/developer-content/blob/main/CONTRIBUTING.md#heading-styles which currently mentions not to use code in headers.
