### ISSUE TITLE
"Add Solana to Your Exchange" page not working

### ISSUE THREAD

**Issue by JustAnotherDevv** [solana-foundation/developer-content#61]
The page "[Add Solana to Your Exchange](https://solana.com/docs/more/exchange)" in the "more information" section is not working properly.

![image](https://github.com/solana-foundation/developer-content/assets/61601037/9216550c-f998-4311-9041-aa636eb15b40)

**Comment by nickfrosty** [comment]
There was a bug in displaying the docs. This has been resolved and this page is now live and well
