### ISSUE TITLE
"Unhappy Path" Documentation

### ISSUE THREAD

**Issue by spacemandev-git** [solana-foundation/developer-content#67]
In the Solana docs there is a lot of good docs on the "happy" path of getting something to work but not a lot of help for developers that get stuck on something that is off the unhappy path.

It'd be helpful to create developer content that identifies how to properly debug and solve issues when building novel solutions, instead of just trying to run working examples. 

Examples of these tools might include the usage of the Solana explorer inspector, propper logging tools, resources to get help, error and logs macros, etc

**Comment by nickfrosty** [comment]
100% agree on all of this!
