### ISSUE TITLE
no such thing as Dis-inflation, its just called deflation

### ISSUE THREAD

**Issue by lopezdp** [solana-foundation/developer-content#74]
your deflation rate is -15%

just wanted to point out a misspelling

its Inflation vs Deflation 

just FYI - it would be cool to work on a project that has its economic terms figured out before I start dealing with structs and pointers

here is the doc with the incorrect term:

https://github.com/solana-foundation/developer-content/blob/main/docs/economics/inflation/inflation_schedule.md

just like precision and lowercase writing styles. thanks.

**Comment by nickfrosty** [comment]
Disinflation is a real word and is different than deflation: https://www.investopedia.com/ask/answers/032415/what-difference-between-deflation-and-disinflation.asp#:~:text=Deflation%20occurs%20when%20the%20inflation,but%20at%20a%20slower%20rate.
