### ISSUE TITLE
Token Extensions Improvements

### ISSUE THREAD

**Issue by jacobcreech** [solana-foundation/developer-content#80]
The main token extensions page can be improved. Feedback as follows:

> a couple of suggestions on docs-related improvements for extensions - it’d be useful to split up the extensions that go on the mint and the ones that go on the ATA, and / or have a subsection under each extension that explains when it gets initialized and used
for example, requiredMemo on transfer is actually an ATA-level feature and, if i’m understanding correctly, only designates restrictions on inbound transfers to that ATA but not a global token-wide requirement. amazing! CPI Guard is also enabled on the ATA, and some part of confidential transfers is enabled on the ATA
same with token metadata, afaict it needs to be initialized after the metadata pointer as part of a separate transaction. same with group / member alongside their compatriots group pointer, member pointer

**Comment by nickfrosty** [comment]
Based on how the website pages are structured, this is what I am thinking to address these points:
- [ ] In the overview/getting started page for extension, we could setup different tables that explicitly note which needs to be on the mint and on the ATA

- [ ] for each individual token extension guide, we can give an explicit call out near the beginning that states where each extension goes, including if they need to before or after initializing the mint
